max_width = 100
hard_tabs = true # Thanks, guys.
tab_spaces = 2 # I don't expect this to change anything with hard_tabs
newline_style = "Auto"
indent_style = "Block"
use_small_heuristics = "Default"
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
wrap_comments = false # Could change to true
format_code_in_doc_comments = true # Frustrating not to
comment_width = 80
normalize_comments = false
normalize_doc_attributes = true # We all seem to use /// anyway.
license_template_path = ""
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = true #
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Crate" # Unified style
group_imports = "StdExternalCrate" # Unified style
reorder_imports = true
reorder_modules = true
reorder_impl_items = true # makes sense
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_multiline_blocks = false
fn_args_layout = "Tall"
brace_style = "PreferSameLine"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2018" # As it *should* have seen from cargo.toml
version = "Two" # We are running Nightly, backwards-compatibility is clearly not our main concern
inline_attribute_width = 0
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = true # It's clear as-is
force_explicit_abi = true
condense_wildcard_suffixes = true # Consistency
color = "Auto"
required_version = "1.4.37"
unstable_features = true # Again, nightly.
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
ignore = []
emit_mode = "Files"
make_backup = false
