name: Formating

on:
  push:
    paths:
      - '**.rs'
  pull_request:
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2021-04-28
        override: true
    - run: rustup component add rustfmt
    - name: rustfmt
      run: cargo fmt --all -- --check
name